### ISSUE TITLE
Allow ability to load all images in a specified folder for palette.

### ISSUE THREAD

**Issue by zlavere** [zlavere/GroupCMosaicMaker#10]
The GUI should allow the ability to load all the images in a folder. Each
image located in the folder will become a part of the image palette that
will be used to form the mosaic.
Related to #8

**Comment by BrandonEugeneWalker** [comment]
Loading from a folder is done, just need to implement into MVVM.

**Comment by BrandonEugeneWalker** [comment]
Display the number of images loaded instead of the grid view, the grid view is for part 3.
