### ISSUE TITLE
Implement functionality for a grid showing an outline of the blocks to be displayed.

### ISSUE THREAD

**Issue by BrandonEugeneWalker** [zlavere/GroupCMosaicMaker#6]
The grid should change, if the user modifies the block
size. The display of the grid should be able to be turned on and off. The grid should be
displayed in white.

**Comment by BrandonEugeneWalker** [comment]
Instead of editing the image we will try overlaying a transparent image with the lines on top of the loaded image.

**Comment by zlavere** [comment]
Using Grid UI layout elements, I'm drawing a Rectangle for each cell in the grid with a side length specified by the user.

**Comment by BrandonEugeneWalker** [comment]
change grid color to white.
