### ISSUE TITLE
Implement functionality to create two different mosaic types, solid and picture mosaics.

### ISSUE THREAD

**Issue by BrandonEugeneWalker** [zlavere/GroupCMosaicMaker#8]
The solid block mosaic must be created as follows:
i. For each block in the source picture. The average red, green, and blue
color value should be calculated for the entire block of pixels. The
average values should be used to form a new color with every pixel in
the corresponding block in the mosaic image assigned the new color.
For example, given a 2x2 block with the following RGB values for its
four pixels: (100, 150, 50), (120, 170, 45), (200, 50, 30), (180, 50, 37).
The average values for each color channel are (150, 105, 40.5). This is
used to form a new RGB color of (150, 105, 40). This new color would
be assigned to all four of the corresponding pixels in the mosaic image.
b. The picture mosaic must be created as follows:
i. The GUI should allow the ability to load all the images in a folder. Each
image located in the folder will become a part of the image palette that
will be used to form the mosaic.
ii. The palette of images will be used as follows:
The source image will be analyzed as before, with a grid size
specified and then each block of the source image analyzed to
compute its average color for each color channel. The average color
for each channel will then be compared to the average color for each
channel of every image in the color palette to find the image with
the best match. Once the image with the best match is found the
entire palette image is mapped into the corresponding block for the
mosaic image. 
When calculating the average color for the palette images the entire
image must be used regardless of the grid size.
To make this requirement a little easier, you may assume that all
images used for the image palette will be square images. The
Images.zip file supplied contains a set of 50x50 images that can be
used. There are over 500 images in the zip file. If all the images were
located in a single folder then your program should be capable of
having all the images loaded into the image palette.
iii. After loading a folder of images, the application should display how
many images are in the image palette.
iv. If a file in the folder of images selected to be the image palette is not a
valid image that file should just be skipped when loading the image.
There is no need to inform the user of this.
v. With the additional functionality of being able to use an image palette
to create the mosaic, add functionality to the application that allows the
user to choose whether to create the mosaic using color blocks or an
image palette.
vi. Only allow selection of the use of the image palette if the user has
already loaded a folder of images.

**Comment by zlavere** [comment]
@BrandonEugeneWalker I'm thinking we can break this up into several issues to help track better :)

**Comment by BrandonEugeneWalker** [comment]
Yeah, I was just getting the basics in first.
